### ISSUE TITLE
Broken Link, and Separation

### ISSUE THREAD

**Issue by karimbakhshamiry** [jawad-hakimee/Afghan-Recipes-Assignment#1]
https://github.com/jawad-hakimee/Afghan-Recipes-Assignment/blob/b7d6b9c22282a7242e2e38122f6bdee4a7a6c4a6/index.html#L12C1-L12C37

It was great Jawad. But it would be better if you could separate each recipe in a different page, and then put a link of them in your main page. Besides, There is one single file here, and there is an image which does not exists in your repository. Can you make sure you separate the recipes, and add the missing image to your repository, please?

**Comment by jawad-hakimee** [comment]
Thanks Dear Karim Baksh!
At the first I did it what you mention then I change my mind to create a new thing.
Now I did  what you said I complete it.
